### PR TITLE
[Bug] Fix inbox archive fails after processing

### LINKED ISSUE #188: User registration agent: processed emails not archived in Outlook
## Summary

After the user registration agent processes an inbox message and the user is successfully created in the database, the source email is **not** moved to archive (or otherwise removed from the inbox). The message remains in the inbox and appears as read in Outlook.

## Expected behavior

Once processing completes successfully and the user exists in our DB, the corresponding email should be archived (or moved out of the primary inbox) consistent with our intended workflow.

## Actual behavior

Emails stay in the inbox and show as read in Outlook.

## Context

- **Area:** `apps/mediapulse/agents/user-registration` (user registration agent)
- **Symptom:** Inbox not cleared/archived after successful user creation

## Notes

- Reproduction steps and environment (tenant, mailbox) can be added when investigated.

### PR DESCRIPTION
**Pull request by sapiderman**
## Summary

**fix: Archive inbox message even when confirm API fails (#188)**

## Problem

After the user-registration agent successfully registered a new subscriber, it called `userRegistrationConfirm.create()` before archiving the Outlook message. If the confirm API threw (e.g. network timeout, DB error), the outer `try/catch` caught the exception and left the message unarchived.

Outlook automatically marks the email as read on first processing, so the `isUnread: true` filter permanently skipped it on all future runs — leaving the user stuck in a half-registered state with no way to recover without manual intervention.

## Fix

Isolated `userRegistrationConfirm.create()` in its own inner `try/catch`. On failure, the error is logged and execution falls through to `archiveMessage()`. This ensures the inbox is always cleared regardless of the confirm API's availability.

The outer `try/catch` around `userRegistration.create()` is intentionally unchanged — a registration failure should still leave the message unarchived so it can be retried on the next run.

## Changes

- index.ts — wrap `confirmCreate` call in inner try/catch
- index.test.ts — add test: "archives message even if confirm API throws"

## Testing

All 14 agent tests pass (`pnpm --filter @mediapulse/user-registration-agent test`).

## Checklist (`.cursor` rules)

- [ ] I ran `pnpm code-quality` locally and it passed.
- [ ] I ran `pnpm cursor:review -- --base origin/main --head HEAD` (or equivalent SHAs) and fixed any issues.
- [ ] **Reuse before create:** I searched for existing components/utilities and reused or extended them instead of duplicating patterns.
- [ ] **Route actions / handlers:** If I added or changed `route.*.config.ts` files, I followed the route-action-gen workflow (config + generator + tests).
- [ ] **Agent Data API:** If I touched `agent-data-api` routes, the shared contract, or the SDK, I updated schemas, manifest, handlers, consumers, and `dev-docs/docs/mediapulse/apps/agent-data-api.mdx` together.
- [ ] **Docs:** I updated dev-docs when behavior or contracts changed.

### CODE REVIEW

File: apps/mediapulse/agents/user-registration/src/index.ts [hunk 1]
```diff
@@ -149,12 +149,19 @@ const app = createAgentApp<
...
-                graphMessageId: msg.id,
-              },
-            });
+            try {
+              await dataApiClient.userRegistrationConfirm.create({
+                userTickerId: registerResponse.userTickerId!,
+                audit: {
+                  graphMessageId: msg.id,
+                },
+              });
```
Comment (nicnocquee) [inline apps/mediapulse/agents/user-registration/src/index.ts]: it seems like the current implementation of `userRegistrationConfirm` is not useful. Using the mailto-flow registration, the `userRegistrationConfirm` now doesn't actually capture any useful information. The user and user ticker are created immediately from the email in the inbox so the `registrationConfirmedAt` in the database can just be set immediately upon creating the user ticker.

What could be useful in this case is to capture the result `await resend.emails.send({` above. But if the email sending via resend is successful, we don't really need to store the result. 

So should we still keep this `dataApiClient.userRegistrationConfirm.create(`?

**Review by nicnocquee — CHANGES_REQUESTED** [review]

File: apps/mediapulse/agents/user-registration/src/index.ts (hunk 1 above)
Comment (sapiderman) [reply apps/mediapulse/agents/user-registration/src/index.ts]: yes good cattch. updated.

**Review by nicnocquee — APPROVED** [review]
